# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nis}
  s.version = "0.1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Takaaki Tateishi"]
  s.date = %q{2010-10-07}
  s.description = %q{Provides an interface for NIS(YP) API.}
  s.email = %q{ttate@users.sourceforge.net}
  s.extensions = ["ext/nis/extconf.rb"]
  s.extra_rdoc_files = [
    "README.html",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG.rdoc",
     "MANIFEST",
     "README.html",
     "README.rdoc",
     "Rakefile",
     "doc/NIS-HOWTO.html",
     "ext/nis/extconf.rb",
     "ext/nis/nis.c",
     "ext/nis/nis.h",
     "ext/nis/yp.c",
     "lib/nis.rb",
     "lib/nis/nis.so",
     "lib/nis/version.rb",
     "nis.gemspec",
     "test/yp_all.rb",
     "test/yp_all2.rb",
     "test/yp_first.rb",
     "test/yp_match.rb"
  ]
  s.homepage = %q{http://raa.ruby-lang.org/project/ruby-nis/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Provides an interface for NIS(YP) API.}
  s.test_files = [
    "test/yp_all.rb",
     "test/yp_first.rb",
     "test/yp_match.rb",
     "test/yp_all2.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

